"""add updated_at and assigned_id to task

Revision ID: ca36717152ab
Revises: 500df6378a9f
Create Date: 2026-06-23 19:18:29.036443

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca36717152ab"
down_revision: Union[str, Sequence[str], None] = "500df6378a9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("assignee_id", sa.UUID(), nullable=True), schema="task"
    )
    op.add_column(
        "tasks",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema="task",
    )
    op.drop_constraint(op.f("tasks_title_key"), "tasks", schema="task", type_="unique")
    # ### end Alembic commands ###
    op.drop_constraint("tasks_pkey", "tasks", schema="task", type_="primary")
    op.create_primary_key("tasks_pkey", "tasks", ["id"], schema="task")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("tasks_title_key"),
        "tasks",
        ["title"],
        schema="task",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("tasks", "updated_at", schema="task")
    op.drop_column("tasks", "assignee_id", schema="task")
    # ### end Alembic commands ###

    op.drop_constraint("tasks_pkey", "tasks", schema="task", type_="primary")
    op.create_primary_key(
        "tasks_pkey", "tasks", ["id", "project_id", "org_id"], schema="task"
    )
