"""add project membership

Revision ID: f41d9752abcd
Revises: 76a65f973861
Create Date: 2026-06-23 20:18:07.954640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41d9752abcd'
down_revision: Union[str, Sequence[str], None] = '76a65f973861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_memberships',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='project'
    )
    op.create_index(op.f('ix_project_project_memberships_org_id'), 'project_memberships', ['org_id'], unique=False, schema='project')
    op.create_index(op.f('ix_project_project_memberships_project_id'), 'project_memberships', ['project_id'], unique=False, schema='project')
    op.create_index(op.f('ix_project_project_memberships_user_id'), 'project_memberships', ['user_id'], unique=False, schema='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_project_memberships_user_id'), table_name='project_memberships', schema='project')
    op.drop_index(op.f('ix_project_project_memberships_project_id'), table_name='project_memberships', schema='project')
    op.drop_index(op.f('ix_project_project_memberships_org_id'), table_name='project_memberships', schema='project')
    op.drop_table('project_memberships', schema='project')
    # ### end Alembic commands ###
