"""add unique_membership_constraint

Revision ID: 7558ad85398a
Revises: f26179cc06d0
Create Date: 2026-06-09 17:30:14.199637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7558ad85398a'
down_revision: Union[str, Sequence[str], None] = 'f26179cc06d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_org_membership_org_user', 'organization_memberships', ['org_id', 'user_id'], schema='org')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_org_membership_org_user', 'organization_memberships', schema='org', type_='unique')
    # ### end Alembic commands ###
