"""create org and membership tables

Revision ID: f26179cc06d0
Revises: 
Create Date: 2026-06-08 19:59:55.121185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26179cc06d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_memberships',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='org'
    )
    op.create_index(op.f('ix_org_organization_memberships_org_id'), 'organization_memberships', ['org_id'], unique=False, schema='org')
    op.create_index(op.f('ix_org_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False, schema='org')
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='org'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations', schema='org')
    op.drop_index(op.f('ix_org_organization_memberships_user_id'), table_name='organization_memberships', schema='org')
    op.drop_index(op.f('ix_org_organization_memberships_org_id'), table_name='organization_memberships', schema='org')
    op.drop_table('organization_memberships', schema='org')
    # ### end Alembic commands ###
